name: publish
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  USERNAME: ${{ github.actor }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      run: |
        echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ env.USERNAME }} --password-stdin
        docker tag IMAGE_ID ghcr.io/${{ env.IMAGE_NAME }}:latest
        docker push ghcr.io/OWNER/${{ env.IMAGE_NAME }}:latest
