name: publish
on: [push]

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build the hello-docker Docker image
      run: |
             cd sample-packages/docker
             docker build . --tag ghcr.io/deselikem/hello-docker-gcr-demo:latest
             docker run ghcr.io/deselikem/hello-docker-gcr-demo:latest
             docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest
